# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'


def shared_pods
  # Pods for News
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
end

target 'News' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  shared_pods
end

target 'News-Dev' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  shared_pods
end

target 'NewsTests' do
  inherit! :search_paths
  # Pods for testing
end

target 'NewsUITests' do
  inherit! :search_paths
  # Pods for testing
end

